// <auto-generated />
using System;
using AISupportTriage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AISupportTriage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816204513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("AISupportTriage.Models.Entities.KnownIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("KnownIssues");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.TicketStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("TicketStatusHistories");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.TriageRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TriageResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TriageResultId");

                    b.ToTable("TriageRecommendations");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.TriageResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnalyzedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KnownIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LikelyCause")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupportTicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KnownIssueId");

                    b.HasIndex("SupportTicketId");

                    b.ToTable("TriageResults");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.TicketStatusHistory", b =>
                {
                    b.HasOne("AISupportTriage.Models.Entities.SupportTicket", "SupportTicket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.TriageRecommendation", b =>
                {
                    b.HasOne("AISupportTriage.Models.Entities.TriageResult", "TriageResult")
                        .WithMany("Recommendations")
                        .HasForeignKey("TriageResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TriageResult");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.TriageResult", b =>
                {
                    b.HasOne("AISupportTriage.Models.Entities.KnownIssue", "KnownIssue")
                        .WithMany("TriageResults")
                        .HasForeignKey("KnownIssueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AISupportTriage.Models.Entities.SupportTicket", "SupportTicket")
                        .WithMany("TriageResults")
                        .HasForeignKey("SupportTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownIssue");

                    b.Navigation("SupportTicket");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.KnownIssue", b =>
                {
                    b.Navigation("TriageResults");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.SupportTicket", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("TriageResults");
                });

            modelBuilder.Entity("AISupportTriage.Models.Entities.TriageResult", b =>
                {
                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
